# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :temp do
    result_bundle_path = File.join("#{Dir.pwd}", "uitest_output")
    puts "Current working directory before: #{result_bundle_path}"
  end

  desc "UIテスト"
  lane :test do |options|
    result_bundle_path = File.join("#{Dir.pwd}", "uitest_output")
    scan(
      project: "UITestSample.xcodeproj",
      scheme: "UITestSample",
      destination: "platform=iOS Simulator,OS=16.2,name=iPhone 14",
      configuration: "Debug",
      result_bundle: result_bundle_path,
      output_directory: result_bundle_path,
      skip_slack: true,
      include_simulator_logs: false,
      clean: true
    )
    sh("xchtmlreport -r #{result_bundle_path}/UITestSample.xcresult")
  end

  before_all do |lane|
    ensure_xcode_version
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end

end
