name: Fastlane-Test-Parallel

on:
  workflow_dispatch:
# on:
#   push:
#     branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_14.2.app

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        # Not needed with a .ruby-version file
        ruby-version: 2.7
        # runs 'bundle install' and caches installed gems automatically
        bundler-cache: true
    - name: Build
      run: bundle exec fastlane build_for_ui_test
      timeout-minutes: 30
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: build-fastlane

  test:
    needs: build
    runs-on: macOS-latest
    strategy:
      matrix:
        tests: [
          "UITestSampleUITests/SampleUITest1/testメインページのテスト1",
          "UITestSampleUITests/SampleUITest2/testサブページのテスト1",
          "UITestSampleUITests/SampleUITest1/testメインページのテスト1",
          "UITestSampleUITests/SampleUITest2/testサブページのテスト1"
        ]
    steps:
    - uses: actions/checkout@v3
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: build-artifact
        path: build-fastlane
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        # Not needed with a .ruby-version file
        ruby-version: 2.7
        # runs 'bundle install' and caches installed gems automatically
        bundler-cache: true
    - name: Test
      run: bundle exec fastlane ui_test_without_building tests:${{ matrix.tests }}
      timeout-minutes: 30
