name: CI

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_14.2.app

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Build
      run: xcodebuild -sdk iphonesimulator -configuration Debug build

  # test:
  #   runs-on: macOS-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Show Xcode version
  #     run: xcodebuild -version
  #   - name: Test
  #     run: xcodebuild -sdk iphonesimulator -scheme UITestSample -destination OS=16.2,name="iPhone 14" -configuration Debug test -resultBundlePath uitest_output/UITestSample.xcresult
  #   - name: Make Report
  #     run: xchtmlreport -r uitest_output/UITestSample.xcresult

  test-with-fastlane:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - name: Show Xcode version
      run: xcodebuild -version
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        # Not needed with a .ruby-version file
        ruby-version: 2.7
        # runs 'bundle install' and caches installed gems automatically
        bundler-cache: true
    - name: TestWithFastlane
      run: bundle exec fastlane test
      timeout-minutes: 30
    # - store_artifacts:
    #   path: ./fastlane/uitest_output
    #   when: always
    - name: Archive test results
      uses: actions/upload-artifact@v3
      with:
        name: uitest-report
        path: fastlane/uitest_output
        when: always
